export const SET_SECTORS = "SET_SECTORS";
export const FETCH_SECTORS_FAILED = "FETCH_SECTORS_FAILED";

export const SET_BUSINESSTYPES = "SET_BUSINESSTYPES";
export const FETCH_BUSINESSTYPES_FAILED = "FETCH_BUSINESSTYPES_FAILED";

export const SET_BUSINESSES = "SET_BUSINESSES";
export const FETCH_BUSINESSES_FAILED = "FETCH_BUSINESSES_FAILED";

export const SET_BUSINESS_DETAIL = "SET_BUSINESS_DETAIL";
export const FETCH_BUSINESS_DETAIL_FAILED = "FETCH_BUSINESS_DETAIL";

export const SET_BUSINESS_PROVIDING_SERVICES =
  "SET_BUSINESS_PROVIDING_SERVICES";
export const FETCH_BUSINESS_PROVIDING_SERVICES_FAILED =
  "FETCH_BUSINESS_PROVIDING_SERVICES_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ERROR_CLEAR = "AUTH_ERROR_CLEAR";
